name: dart_zx
description: Bash is great, but when it comes to writing more complex scripts, many people prefer a more convenient programming language. Dart is a perfect choice, but the DartIO standard library requires additional hassle before using. The zx package provides useful wrappers around child_process, escapes arguments and gives sensible defaults.
version: 1.0.0

environment:
  sdk: ^3.4.3

dependencies:
  ansicolor: ^2.0.3
  pretty_dio_logger: ^1.4.0
  async: ^2.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
